# nonk8s
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/infra-dev/*
build:
    local:
        push: false

    artifacts:
        # Auth-API service
        - image: espressotrip/concept-auth-api
          context: auth/auth-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Auth-Service service
        - image: espressotrip/concept-auth-service
          context: auth/auth-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

      # Analytic-API service
        - image: espressotrip/concept-analytic-api
          context: analytic/analytic-api
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .

      # Analytic-Service service
        - image: espressotrip/concept-analytic-service
          context: analytic/analytic-service
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .

      # Log-Service service
        - image: espressotrip/concept-log-service
          context: log/log-service
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .

        # Auth-Web service
        - image: espressotrip/concept-auth-web
          context: auth/auth-web
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.jsx"
                    dest: .
                  - src: "src/**/*.js"
                    dest: .