# nonk8s
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/infra-dev/*
build:
    local:
        push: false

    artifacts:
        # Auth-API service
        - image: espressotrip/concept-auth-api
          context: auth/auth-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Auth-Service service
        - image: espressotrip/concept-auth-service
          context: auth/auth-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Analytic-API service
        - image: espressotrip/concept-analytic-api
          context: analytic/analytic-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Analytic-Service service
        - image: espressotrip/concept-analytic-service
          context: analytic/analytic-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Employee-API service
        - image: espressotrip/concept-employee-api
          context: employee/employee-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Employee-Service service
        - image: espressotrip/concept-employee-service
          context: employee/employee-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Employee-Dash-API service
        - image: espressotrip/concept-employee-dash-api
          context: employee-dash/employee-dash-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Employee-Dash-Service service
        - image: espressotrip/concept-employee-dash-service
          context: employee-dash/employee-dash-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.go"
                    dest: .

        # Log-Service service
        - image: espressotrip/concept-log-service
          context: log/log-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Task-API service
        - image: espressotrip/concept-task-api
          context: task/task-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.go"
                    dest: .

        # Task-Service service
        - image: espressotrip/concept-task-service
          context: task/task-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.go"
                    dest: .

        # Web UI
        - image: espressotrip/concept-auth-web
          context: web-ui
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.jsx"
                    dest: .
                  - src: "src/**/*.js"
                    dest: .
                  - src: "src/**/*.css"
                    dest: .
                  - src: "src/**/*.scss"
                    dest: .

        # Employee UI
        - image: espressotrip/concept-employee-ui
          context: employee-ui
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.jsx"
                    dest: .
                  - src: "src/**/*.js"
                    dest: .
                  - src: "src/**/*.css"
                    dest: .
                  - src: "src/**/*.scss"
                    dest: .
                  - src: "src/**/*.ts"
                    dest: .
                  - src: "src/**/*.tsx"
                    dest: .
