# nonk8s
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/*
build:
    local:
        push: false
    #
    artifacts:
        #    # Auth service
        #    - image: espressotrip/concept-auth
        #      context: auth
        #      docker:
        #        dockerfile: Dockerfile
        #      sync:
        #        manual:
        #          - src: "src/**/*.ts"
        #            dest: .
        #    # Product service
        - image: espressotrip/concept-product
          context: product
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
#    # Order service
#    - image: espressotrip/concept-order
#      context: order
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: "src/**/*.ts"
#            dest: .
