# nonk8s
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/*
build:
    local:
        push: false

    artifacts:
        # Auth service
        - image: espressotrip/concept-auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          # Product service
        - image: espressotrip/concept-product
          context: product
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Analytic service
        - image: espressotrip/concept-analytic
          context: product
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Client service
        - image: espressotrip/concept-client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
