# nonk8s
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/*
build:
    local:
        push: false

    artifacts:
        # Auth-API service
        - image: espressotrip/concept-auth-api
          context: auth/auth-api
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Auth-Service service
        - image: espressotrip/concept-auth-service
          context: auth/auth-service
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Product service
        - image: espressotrip/concept-product
          context: product
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Analytic service
        - image: espressotrip/concept-analytic
          context: analytic
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .

        # Client service
        - image: espressotrip/concept-auth-web
          context: auth/auth-web
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
