// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package userPackage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Race                 string   `protobuf:"bytes,5,opt,name=race,proto3" json:"race,omitempty"`
	Position             string   `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	StartDate            string   `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	ShiftPreference      string   `protobuf:"bytes,8,opt,name=shiftPreference,proto3" json:"shiftPreference,omitempty"`
	BranchName           string   `protobuf:"bytes,9,opt,name=branchName,proto3" json:"branchName,omitempty"`
	Region               string   `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Country              string   `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,12,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	Version              int32    `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	SignInType           string   `protobuf:"bytes,15,opt,name=signInType,proto3" json:"signInType,omitempty"`
	ProviderId           string   `protobuf:"bytes,16,opt,name=providerId,proto3" json:"providerId,omitempty"`
	Password             string   `protobuf:"bytes,17,opt,name=password,proto3" json:"password,omitempty"`
	UserRole             string   `protobuf:"bytes,18,opt,name=userRole,proto3" json:"userRole,omitempty"`
	RegisteredEmployee   string   `protobuf:"bytes,19,opt,name=registeredEmployee,proto3" json:"registeredEmployee,omitempty"`
	Division             string   `protobuf:"bytes,20,opt,name=division,proto3" json:"division,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcUser) Reset()         { *m = GrpcUser{} }
func (m *GrpcUser) String() string { return proto.CompactTextString(m) }
func (*GrpcUser) ProtoMessage()    {}
func (*GrpcUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *GrpcUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcUser.Unmarshal(m, b)
}
func (m *GrpcUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcUser.Marshal(b, m, deterministic)
}
func (m *GrpcUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcUser.Merge(m, src)
}
func (m *GrpcUser) XXX_Size() int {
	return xxx_messageInfo_GrpcUser.Size(m)
}
func (m *GrpcUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcUser.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcUser proto.InternalMessageInfo

func (m *GrpcUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GrpcUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GrpcUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GrpcUser) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *GrpcUser) GetRace() string {
	if m != nil {
		return m.Race
	}
	return ""
}

func (m *GrpcUser) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *GrpcUser) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *GrpcUser) GetShiftPreference() string {
	if m != nil {
		return m.ShiftPreference
	}
	return ""
}

func (m *GrpcUser) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *GrpcUser) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GrpcUser) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GrpcUser) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *GrpcUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GrpcUser) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GrpcUser) GetSignInType() string {
	if m != nil {
		return m.SignInType
	}
	return ""
}

func (m *GrpcUser) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *GrpcUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GrpcUser) GetUserRole() string {
	if m != nil {
		return m.UserRole
	}
	return ""
}

func (m *GrpcUser) GetRegisteredEmployee() string {
	if m != nil {
		return m.RegisteredEmployee
	}
	return ""
}

func (m *GrpcUser) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type AllGrpcUsers struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllGrpcUsers) Reset()         { *m = AllGrpcUsers{} }
func (m *AllGrpcUsers) String() string { return proto.CompactTextString(m) }
func (*AllGrpcUsers) ProtoMessage()    {}
func (*AllGrpcUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *AllGrpcUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllGrpcUsers.Unmarshal(m, b)
}
func (m *AllGrpcUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllGrpcUsers.Marshal(b, m, deterministic)
}
func (m *AllGrpcUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllGrpcUsers.Merge(m, src)
}
func (m *AllGrpcUsers) XXX_Size() int {
	return xxx_messageInfo_AllGrpcUsers.Size(m)
}
func (m *AllGrpcUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_AllGrpcUsers.DiscardUnknown(m)
}

var xxx_messageInfo_AllGrpcUsers proto.InternalMessageInfo

func (m *AllGrpcUsers) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type GoogleGrpcUser struct {
	Sub                  string   `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GivenName            string   `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string   `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Picture              string   `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        string   `protobuf:"bytes,7,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Locale               string   `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleGrpcUser) Reset()         { *m = GoogleGrpcUser{} }
func (m *GoogleGrpcUser) String() string { return proto.CompactTextString(m) }
func (*GoogleGrpcUser) ProtoMessage()    {}
func (*GoogleGrpcUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *GoogleGrpcUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleGrpcUser.Unmarshal(m, b)
}
func (m *GoogleGrpcUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleGrpcUser.Marshal(b, m, deterministic)
}
func (m *GoogleGrpcUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleGrpcUser.Merge(m, src)
}
func (m *GoogleGrpcUser) XXX_Size() int {
	return xxx_messageInfo_GoogleGrpcUser.Size(m)
}
func (m *GoogleGrpcUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleGrpcUser.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleGrpcUser proto.InternalMessageInfo

func (m *GoogleGrpcUser) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *GoogleGrpcUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoogleGrpcUser) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *GoogleGrpcUser) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *GoogleGrpcUser) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *GoogleGrpcUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GoogleGrpcUser) GetEmailVerified() string {
	if m != nil {
		return m.EmailVerified
	}
	return ""
}

func (m *GoogleGrpcUser) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type GitHubGrpcUser struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeId               string   `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	GravatarId           string   `protobuf:"bytes,5,opt,name=gravatar_id,json=gravatarId,proto3" json:"gravatar_id,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	HtmlUrl              string   `protobuf:"bytes,7,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	FollowersUrl         string   `protobuf:"bytes,8,opt,name=followers_url,json=followersUrl,proto3" json:"followers_url,omitempty"`
	FollowingUrl         string   `protobuf:"bytes,9,opt,name=following_url,json=followingUrl,proto3" json:"following_url,omitempty"`
	GistsUrl             string   `protobuf:"bytes,10,opt,name=gists_url,json=gistsUrl,proto3" json:"gists_url,omitempty"`
	StarredUrl           string   `protobuf:"bytes,11,opt,name=starred_url,json=starredUrl,proto3" json:"starred_url,omitempty"`
	SubscriptionsUrl     string   `protobuf:"bytes,12,opt,name=subscriptions_url,json=subscriptionsUrl,proto3" json:"subscriptions_url,omitempty"`
	OrganizationsUrl     string   `protobuf:"bytes,13,opt,name=organizations_url,json=organizationsUrl,proto3" json:"organizations_url,omitempty"`
	ReposUrl             string   `protobuf:"bytes,14,opt,name=repos_url,json=reposUrl,proto3" json:"repos_url,omitempty"`
	EventsUrl            string   `protobuf:"bytes,15,opt,name=events_url,json=eventsUrl,proto3" json:"events_url,omitempty"`
	ReceivedEventsUrl    string   `protobuf:"bytes,16,opt,name=received_events_url,json=receivedEventsUrl,proto3" json:"received_events_url,omitempty"`
	Type                 string   `protobuf:"bytes,17,opt,name=type,proto3" json:"type,omitempty"`
	SiteAdmin            bool     `protobuf:"varint,18,opt,name=site_admin,json=siteAdmin,proto3" json:"site_admin,omitempty"`
	Name                 string   `protobuf:"bytes,19,opt,name=name,proto3" json:"name,omitempty"`
	Company              string   `protobuf:"bytes,20,opt,name=company,proto3" json:"company,omitempty"`
	Blog                 string   `protobuf:"bytes,21,opt,name=blog,proto3" json:"blog,omitempty"`
	Location             string   `protobuf:"bytes,22,opt,name=location,proto3" json:"location,omitempty"`
	Email                string   `protobuf:"bytes,23,opt,name=email,proto3" json:"email,omitempty"`
	Hireable             bool     `protobuf:"varint,24,opt,name=hireable,proto3" json:"hireable,omitempty"`
	Bio                  string   `protobuf:"bytes,25,opt,name=bio,proto3" json:"bio,omitempty"`
	TwitterUsername      string   `protobuf:"bytes,26,opt,name=twitter_username,json=twitterUsername,proto3" json:"twitter_username,omitempty"`
	PublicRepos          int32    `protobuf:"varint,27,opt,name=public_repos,json=publicRepos,proto3" json:"public_repos,omitempty"`
	PublicGists          int32    `protobuf:"varint,28,opt,name=public_gists,json=publicGists,proto3" json:"public_gists,omitempty"`
	Followers            int32    `protobuf:"varint,29,opt,name=followers,proto3" json:"followers,omitempty"`
	Following            int32    `protobuf:"varint,30,opt,name=following,proto3" json:"following,omitempty"`
	CreatedAt            string   `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitHubGrpcUser) Reset()         { *m = GitHubGrpcUser{} }
func (m *GitHubGrpcUser) String() string { return proto.CompactTextString(m) }
func (*GitHubGrpcUser) ProtoMessage()    {}
func (*GitHubGrpcUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *GitHubGrpcUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitHubGrpcUser.Unmarshal(m, b)
}
func (m *GitHubGrpcUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitHubGrpcUser.Marshal(b, m, deterministic)
}
func (m *GitHubGrpcUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitHubGrpcUser.Merge(m, src)
}
func (m *GitHubGrpcUser) XXX_Size() int {
	return xxx_messageInfo_GitHubGrpcUser.Size(m)
}
func (m *GitHubGrpcUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GitHubGrpcUser.DiscardUnknown(m)
}

var xxx_messageInfo_GitHubGrpcUser proto.InternalMessageInfo

func (m *GitHubGrpcUser) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *GitHubGrpcUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GitHubGrpcUser) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GitHubGrpcUser) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetGravatarId() string {
	if m != nil {
		return m.GravatarId
	}
	return ""
}

func (m *GitHubGrpcUser) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GitHubGrpcUser) GetHtmlUrl() string {
	if m != nil {
		return m.HtmlUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetFollowersUrl() string {
	if m != nil {
		return m.FollowersUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetFollowingUrl() string {
	if m != nil {
		return m.FollowingUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetGistsUrl() string {
	if m != nil {
		return m.GistsUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetStarredUrl() string {
	if m != nil {
		return m.StarredUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetSubscriptionsUrl() string {
	if m != nil {
		return m.SubscriptionsUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetOrganizationsUrl() string {
	if m != nil {
		return m.OrganizationsUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetReposUrl() string {
	if m != nil {
		return m.ReposUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetEventsUrl() string {
	if m != nil {
		return m.EventsUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetReceivedEventsUrl() string {
	if m != nil {
		return m.ReceivedEventsUrl
	}
	return ""
}

func (m *GitHubGrpcUser) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GitHubGrpcUser) GetSiteAdmin() bool {
	if m != nil {
		return m.SiteAdmin
	}
	return false
}

func (m *GitHubGrpcUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitHubGrpcUser) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *GitHubGrpcUser) GetBlog() string {
	if m != nil {
		return m.Blog
	}
	return ""
}

func (m *GitHubGrpcUser) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GitHubGrpcUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GitHubGrpcUser) GetHireable() bool {
	if m != nil {
		return m.Hireable
	}
	return false
}

func (m *GitHubGrpcUser) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *GitHubGrpcUser) GetTwitterUsername() string {
	if m != nil {
		return m.TwitterUsername
	}
	return ""
}

func (m *GitHubGrpcUser) GetPublicRepos() int32 {
	if m != nil {
		return m.PublicRepos
	}
	return 0
}

func (m *GitHubGrpcUser) GetPublicGists() int32 {
	if m != nil {
		return m.PublicGists
	}
	return 0
}

func (m *GitHubGrpcUser) GetFollowers() int32 {
	if m != nil {
		return m.Followers
	}
	return 0
}

func (m *GitHubGrpcUser) GetFollowing() int32 {
	if m != nil {
		return m.Following
	}
	return 0
}

func (m *GitHubGrpcUser) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GitHubGrpcUser) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type LocalGrpcUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalGrpcUser) Reset()         { *m = LocalGrpcUser{} }
func (m *LocalGrpcUser) String() string { return proto.CompactTextString(m) }
func (*LocalGrpcUser) ProtoMessage()    {}
func (*LocalGrpcUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{4}
}

func (m *LocalGrpcUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalGrpcUser.Unmarshal(m, b)
}
func (m *LocalGrpcUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalGrpcUser.Marshal(b, m, deterministic)
}
func (m *LocalGrpcUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalGrpcUser.Merge(m, src)
}
func (m *LocalGrpcUser) XXX_Size() int {
	return xxx_messageInfo_LocalGrpcUser.Size(m)
}
func (m *LocalGrpcUser) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalGrpcUser.DiscardUnknown(m)
}

var xxx_messageInfo_LocalGrpcUser proto.InternalMessageInfo

func (m *LocalGrpcUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LocalGrpcUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GrpcResponsePayload struct {
	Status               int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Jwt                  string    `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Data                 *GrpcUser `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GrpcResponsePayload) Reset()         { *m = GrpcResponsePayload{} }
func (m *GrpcResponsePayload) String() string { return proto.CompactTextString(m) }
func (*GrpcResponsePayload) ProtoMessage()    {}
func (*GrpcResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{5}
}

func (m *GrpcResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcResponsePayload.Unmarshal(m, b)
}
func (m *GrpcResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcResponsePayload.Marshal(b, m, deterministic)
}
func (m *GrpcResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcResponsePayload.Merge(m, src)
}
func (m *GrpcResponsePayload) XXX_Size() int {
	return xxx_messageInfo_GrpcResponsePayload.Size(m)
}
func (m *GrpcResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcResponsePayload proto.InternalMessageInfo

func (m *GrpcResponsePayload) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GrpcResponsePayload) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *GrpcResponsePayload) GetData() *GrpcUser {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GrpcUser)(nil), "userPackage.GrpcUser")
	proto.RegisterType((*AllGrpcUsers)(nil), "userPackage.AllGrpcUsers")
	proto.RegisterType((*GoogleGrpcUser)(nil), "userPackage.GoogleGrpcUser")
	proto.RegisterType((*GitHubGrpcUser)(nil), "userPackage.GitHubGrpcUser")
	proto.RegisterType((*LocalGrpcUser)(nil), "userPackage.LocalGrpcUser")
	proto.RegisterType((*GrpcResponsePayload)(nil), "userPackage.GrpcResponsePayload")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 1028 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x51, 0x6e, 0x1b, 0x47,
	0x0f, 0xfe, 0xad, 0xd8, 0x96, 0x44, 0xd9, 0x8a, 0x32, 0x76, 0x92, 0x89, 0x1d, 0x27, 0xfe, 0x55,
	0x14, 0x70, 0x50, 0xc0, 0x2d, 0xd2, 0x13, 0x18, 0x68, 0xe0, 0x1a, 0x08, 0x02, 0x43, 0xad, 0xfb,
	0x2a, 0x8c, 0x76, 0xa9, 0xf5, 0xa4, 0xab, 0x99, 0xc5, 0xcc, 0x48, 0x86, 0x7a, 0x81, 0xde, 0xad,
	0xe8, 0x35, 0x7a, 0x8f, 0x82, 0x9c, 0x59, 0xed, 0xca, 0xcd, 0x43, 0xde, 0xc8, 0xef, 0xfb, 0x96,
	0x26, 0x39, 0x24, 0x65, 0x18, 0x55, 0xce, 0x06, 0xfb, 0xfd, 0xd2, 0xa3, 0xbb, 0x64, 0x53, 0x0c,
	0xc8, 0xbe, 0x55, 0xd9, 0xef, 0xaa, 0xc0, 0xf1, 0xdf, 0xbb, 0xd0, 0xbb, 0x76, 0x55, 0x76, 0xe7,
	0xd1, 0x89, 0x21, 0x74, 0x74, 0x2e, 0x77, 0xce, 0x77, 0x2e, 0xfa, 0x93, 0x8e, 0xce, 0xc5, 0x6b,
	0xe8, 0xcf, 0xb5, 0xf3, 0xe1, 0x93, 0x5a, 0xa0, 0xec, 0x30, 0xdc, 0x00, 0xe2, 0x04, 0x7a, 0xa5,
	0x4a, 0xe4, 0x13, 0x26, 0x37, 0xbe, 0x78, 0x01, 0xfb, 0x05, 0x9a, 0x1c, 0x9d, 0xdc, 0x65, 0x26,
	0x79, 0x42, 0xc0, 0xae, 0x53, 0x19, 0xca, 0x3d, 0x46, 0xd9, 0xa6, 0x38, 0x95, 0xf5, 0x3a, 0x68,
	0x6b, 0xe4, 0x7e, 0x8c, 0x53, 0xfb, 0x94, 0x81, 0x0f, 0xca, 0x85, 0x9f, 0x54, 0x40, 0xd9, 0x8d,
	0x19, 0x6c, 0x00, 0x71, 0x01, 0x4f, 0xfd, 0xbd, 0x9e, 0x87, 0x5b, 0x87, 0x73, 0x74, 0x68, 0x32,
	0x94, 0x3d, 0xd6, 0x3c, 0x86, 0xc5, 0x1b, 0x80, 0x99, 0x53, 0x26, 0xbb, 0xe7, 0x6c, 0xfb, 0x2c,
	0x6a, 0x21, 0x94, 0xaf, 0xc3, 0x82, 0x32, 0x80, 0x98, 0x6f, 0xf4, 0x84, 0x84, 0x6e, 0x66, 0x97,
	0x26, 0xb8, 0xb5, 0x1c, 0x30, 0x51, 0xbb, 0xe2, 0x1c, 0x06, 0xd5, 0xbd, 0x35, 0xf8, 0x69, 0xb9,
	0x98, 0xa1, 0x93, 0x07, 0xcc, 0xb6, 0x21, 0x71, 0x0c, 0x7b, 0xb8, 0x50, 0xba, 0x94, 0x87, 0xcc,
	0x45, 0x87, 0x22, 0xae, 0xd0, 0x79, 0xfa, 0x53, 0xc3, 0xf3, 0x9d, 0x8b, 0xbd, 0x49, 0xed, 0x52,
	0x8e, 0x5e, 0x17, 0xe6, 0xc6, 0xfc, 0xba, 0xae, 0x50, 0x3e, 0x8d, 0x39, 0x36, 0x08, 0xf1, 0x95,
	0xb3, 0x2b, 0x9d, 0xa3, 0xbb, 0xc9, 0xe5, 0x28, 0xf2, 0x0d, 0xc2, 0x7d, 0x54, 0xde, 0x3f, 0x58,
	0x97, 0xcb, 0x67, 0xa9, 0x8f, 0xc9, 0x27, 0x8e, 0x5e, 0x7d, 0x62, 0x4b, 0x94, 0x22, 0x72, 0xb5,
	0x2f, 0x2e, 0x41, 0x50, 0xb5, 0x3e, 0xa0, 0xc3, 0xfc, 0xc3, 0xa2, 0x2a, 0xed, 0x1a, 0x51, 0x1e,
	0xb1, 0xea, 0x0b, 0x0c, 0xc5, 0xca, 0xf5, 0x4a, 0x73, 0x09, 0xc7, 0x31, 0x56, 0xed, 0x8f, 0x7f,
	0x80, 0x83, 0xab, 0xb2, 0xac, 0x07, 0xca, 0x53, 0x97, 0x3c, 0xba, 0x95, 0xce, 0x90, 0x1b, 0x1f,
	0x47, 0xab, 0x0d, 0x8d, 0xff, 0xd9, 0x81, 0xe1, 0xb5, 0xb5, 0x45, 0x89, 0x9b, 0x31, 0x1c, 0xc1,
	0x13, 0xbf, 0x9c, 0x25, 0x31, 0x99, 0x34, 0x36, 0xa6, 0x99, 0x41, 0xb6, 0xc5, 0x19, 0x40, 0xa1,
	0x57, 0x68, 0xa6, 0xa6, 0x19, 0xc0, 0x3e, 0x23, 0xfc, 0xa2, 0x6f, 0x61, 0x30, 0x57, 0x0b, 0x5d,
	0xae, 0x23, 0x1f, 0xc7, 0x10, 0x22, 0xc4, 0x02, 0x09, 0xdd, 0x4a, 0x67, 0x61, 0xe9, 0xea, 0x69,
	0xac, 0xdd, 0xe6, 0xe1, 0xf6, 0xdb, 0x0f, 0xf7, 0x2d, 0x0c, 0xd9, 0x98, 0xae, 0xd0, 0xe9, 0xb9,
	0xc6, 0x3c, 0xcd, 0xe3, 0x21, 0xa3, 0xbf, 0x25, 0x90, 0x26, 0xa9, 0xb4, 0x99, 0x2a, 0xeb, 0x51,
	0x4c, 0xde, 0xf8, 0xaf, 0x2e, 0x0c, 0xaf, 0x75, 0xf8, 0x79, 0x39, 0xdb, 0xd4, 0x79, 0x0c, 0x7b,
	0xa5, 0x2d, 0xb4, 0x49, 0x95, 0x46, 0x27, 0x2d, 0x61, 0x87, 0x67, 0x83, 0x96, 0xf0, 0x25, 0x74,
	0x8d, 0xcd, 0x71, 0xaa, 0xf3, 0x54, 0xe4, 0x3e, 0xb9, 0x37, 0x39, 0x35, 0x40, 0xad, 0x54, 0x50,
	0x6e, 0xba, 0x74, 0x65, 0x2a, 0xb0, 0x1f, 0x91, 0x3b, 0x57, 0x52, 0x03, 0x0a, 0x97, 0x04, 0x3a,
	0x4f, 0x35, 0x42, 0x0d, 0xdd, 0xe4, 0xd4, 0x66, 0xfa, 0x30, 0x16, 0x49, 0xa6, 0x78, 0x05, 0xbd,
	0xfb, 0xb0, 0x28, 0x39, 0x5e, 0x2c, 0xae, 0x4b, 0x3e, 0x45, 0xfb, 0x06, 0x0e, 0xe7, 0xb6, 0x2c,
	0xed, 0x03, 0x3a, 0xcf, 0x7c, 0xac, 0xee, 0x60, 0x03, 0x6e, 0x89, 0xb4, 0x29, 0x58, 0xd4, 0x6f,
	0x8b, 0xb4, 0x29, 0x48, 0x74, 0x0a, 0x7d, 0x1a, 0xa9, 0x18, 0x25, 0x6e, 0x5b, 0x8f, 0x81, 0x94,
	0x34, 0xad, 0xb7, 0xc3, 0x9c, 0xe9, 0x41, 0x5a, 0x82, 0x08, 0x91, 0xe0, 0x3b, 0x78, 0xe6, 0x97,
	0x33, 0x9f, 0x39, 0x5d, 0xd1, 0x81, 0x88, 0x51, 0xe2, 0xf2, 0x8d, 0xb6, 0x88, 0x24, 0xb6, 0xae,
	0x50, 0x46, 0xff, 0xa1, 0x1a, 0x71, 0xdc, 0xc6, 0xd1, 0x16, 0x91, 0xf2, 0x72, 0x58, 0xd9, 0x28,
	0x1a, 0xc6, 0xbc, 0x18, 0x20, 0xf2, 0x0c, 0x00, 0x57, 0x68, 0x52, 0xd6, 0x71, 0x37, 0xfb, 0x11,
	0x21, 0xfa, 0x12, 0x8e, 0x1c, 0x66, 0xa8, 0x57, 0x98, 0x4f, 0x5b, 0xba, 0xb8, 0xa3, 0xcf, 0x6a,
	0xea, 0xc3, 0x46, 0x2f, 0x60, 0x37, 0xd0, 0x92, 0xc7, 0x35, 0x65, 0x9b, 0xfe, 0x84, 0xd7, 0x01,
	0xa7, 0x2a, 0x5f, 0x68, 0xc3, 0x4b, 0xda, 0x9b, 0xf4, 0x09, 0xb9, 0x22, 0x60, 0xb3, 0x02, 0x47,
	0xad, 0x15, 0xe0, 0xeb, 0xb4, 0xa8, 0x94, 0x59, 0xa7, 0x45, 0xac, 0x5d, 0x52, 0xcf, 0x4a, 0x5b,
	0xc8, 0xe7, 0x51, 0x4d, 0x36, 0xdf, 0x6b, 0x9b, 0x71, 0xc1, 0xf2, 0x45, 0xba, 0xd7, 0xc9, 0x6f,
	0x46, 0xfe, 0x65, 0x7b, 0xe4, 0x4f, 0xa0, 0x77, 0xaf, 0x1d, 0xaa, 0x59, 0x89, 0x52, 0x72, 0x42,
	0x1b, 0x9f, 0xa6, 0x67, 0xa6, 0xad, 0x7c, 0x15, 0xa7, 0x67, 0xa6, 0xad, 0x78, 0x07, 0xa3, 0xf0,
	0xa0, 0x43, 0x40, 0x37, 0xa5, 0xdb, 0xc2, 0xd9, 0x9e, 0xc4, 0x73, 0x9c, 0xf0, 0xbb, 0x04, 0x8b,
	0xff, 0xc3, 0x41, 0xb5, 0x9c, 0x95, 0x3a, 0x9b, 0x72, 0x87, 0xe5, 0x29, 0x4f, 0xfb, 0x20, 0x62,
	0x13, 0x82, 0x5a, 0x12, 0x1e, 0x0e, 0xf9, 0xba, 0x2d, 0xb9, 0x26, 0x88, 0x7f, 0x9e, 0xea, 0xf1,
	0x93, 0x67, 0xcc, 0x37, 0x40, 0xc3, 0x6a, 0x53, 0xc8, 0x37, 0x6d, 0x56, 0x9b, 0x82, 0xba, 0x9d,
	0x39, 0x54, 0x01, 0xf3, 0xa9, 0x0a, 0xf2, 0x6d, 0x7c, 0xd0, 0x84, 0x5c, 0x05, 0xa2, 0x97, 0x55,
	0x5e, 0xd3, 0xe7, 0x91, 0x4e, 0xc8, 0x55, 0x18, 0x5f, 0xc1, 0xe1, 0x47, 0x5a, 0xeb, 0xf6, 0x2a,
	0xc7, 0xfe, 0xed, 0x3c, 0xea, 0xdf, 0xe6, 0x22, 0x77, 0xb6, 0x2f, 0xf2, 0xf8, 0x33, 0x1c, 0xd1,
	0xd7, 0x13, 0xf4, 0x95, 0x35, 0x1e, 0x6f, 0xd5, 0xba, 0xb4, 0x8a, 0xcf, 0x87, 0x0f, 0x2a, 0x2c,
	0x3d, 0x47, 0xda, 0x9b, 0x24, 0x8f, 0xda, 0xfd, 0xf9, 0x21, 0xa4, 0x28, 0x64, 0x8a, 0x77, 0xb0,
	0x9b, 0xab, 0xa0, 0xf8, 0x28, 0x0c, 0xde, 0x3f, 0xbf, 0x6c, 0xfd, 0xaa, 0x5f, 0xd6, 0x79, 0x4d,
	0x58, 0xf2, 0xfe, 0xcf, 0x0e, 0x0c, 0xc8, 0xfd, 0x25, 0xde, 0x5d, 0x31, 0x81, 0xa7, 0x1f, 0xe9,
	0xd6, 0xc4, 0xbb, 0xcb, 0x05, 0x9c, 0x6e, 0x7f, 0xbf, 0x75, 0x90, 0x4f, 0xce, 0xff, 0x13, 0xfc,
	0x51, 0xda, 0xe3, 0xff, 0x35, 0x31, 0xf9, 0xc6, 0x7d, 0x29, 0xe6, 0xd6, 0xf1, 0xfb, 0xaa, 0x98,
	0xb7, 0x30, 0xe4, 0x98, 0xdc, 0x6b, 0x0e, 0x79, 0xb2, 0xf5, 0xd5, 0xd6, 0x1b, 0x7c, 0x4d, 0xc4,
	0xd9, 0x3e, 0xff, 0x0b, 0xf4, 0xe3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x80, 0x69, 0x29,
	0x16, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	LoginGoogleUser(ctx context.Context, in *GoogleGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error)
	LoginGitHubUser(ctx context.Context, in *GitHubGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error)
	LoginLocalUser(ctx context.Context, in *LocalGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) LoginGoogleUser(ctx context.Context, in *GoogleGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error) {
	out := new(GrpcResponsePayload)
	err := c.cc.Invoke(ctx, "/userPackage.UserService/LoginGoogleUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginGitHubUser(ctx context.Context, in *GitHubGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error) {
	out := new(GrpcResponsePayload)
	err := c.cc.Invoke(ctx, "/userPackage.UserService/LoginGitHubUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginLocalUser(ctx context.Context, in *LocalGrpcUser, opts ...grpc.CallOption) (*GrpcResponsePayload, error) {
	out := new(GrpcResponsePayload)
	err := c.cc.Invoke(ctx, "/userPackage.UserService/LoginLocalUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	LoginGoogleUser(context.Context, *GoogleGrpcUser) (*GrpcResponsePayload, error)
	LoginGitHubUser(context.Context, *GitHubGrpcUser) (*GrpcResponsePayload, error)
	LoginLocalUser(context.Context, *LocalGrpcUser) (*GrpcResponsePayload, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) LoginGoogleUser(ctx context.Context, req *GoogleGrpcUser) (*GrpcResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginGoogleUser not implemented")
}
func (*UnimplementedUserServiceServer) LoginGitHubUser(ctx context.Context, req *GitHubGrpcUser) (*GrpcResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginGitHubUser not implemented")
}
func (*UnimplementedUserServiceServer) LoginLocalUser(ctx context.Context, req *LocalGrpcUser) (*GrpcResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginLocalUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_LoginGoogleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleGrpcUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginGoogleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userPackage.UserService/LoginGoogleUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginGoogleUser(ctx, req.(*GoogleGrpcUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginGitHubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitHubGrpcUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginGitHubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userPackage.UserService/LoginGitHubUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginGitHubUser(ctx, req.(*GitHubGrpcUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginLocalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalGrpcUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginLocalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userPackage.UserService/LoginLocalUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginLocalUser(ctx, req.(*LocalGrpcUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userPackage.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginGoogleUser",
			Handler:    _UserService_LoginGoogleUser_Handler,
		},
		{
			MethodName: "LoginGitHubUser",
			Handler:    _UserService_LoginGitHubUser_Handler,
		},
		{
			MethodName: "LoginLocalUser",
			Handler:    _UserService_LoginLocalUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
