apiVersion: v1
kind: ConfigMap
metadata:
    name: analytic-service-config
data:
    PORT: "3000"
    MONGO_URI: "mongodb://root:8103@analytic-mongo-0.analytic-mongo-svc.default.svc.cluster.local:27017/analytic?ssl=false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: analytic-service-depl
    labels:
        app: analytic-service
spec:
    replicas: 1
    template:
        metadata:
            name: analytic-service
            labels:
                app: analytic-service
        spec:
            containers:
                - name: analytic-service
                  image: espressotrip/concept-analytic-service
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: analytic-service-config
                      - configMapRef:
                            name: global-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: analytic-service

---
apiVersion: v1
kind: Service
metadata:
    name: analytic-service-srv
spec:
    selector:
        app: analytic-service
    ports:
        - port: 8080
          targetPort: 8080
          name: grpc
