apiVersion: v1
kind: ConfigMap
metadata:
    name: product-config
data:
    PORT: "3000"
    MONGO_URI: "mongodb://root:8103@product-mongo-0.product-mongo-svc.default.svc.cluster.local:27017/product?ssl=false"
    RABBIT_URI: "amqp://rabbit-cluster"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: product-depl
    labels:
        app: product
spec:
    replicas: 1
    template:
        metadata:
            name: product
            labels:
                app: product
        spec:
            containers:
                - name: product
                  image: espressotrip/concept-product
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: product-config
                      - configMapRef:
                            name: global-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: product

---
apiVersion: v1
kind: Service
metadata:
    name: product-service
spec:
    selector:
        app: product
    ports:
        - port: 3000
          targetPort: 3000
          name: product
