// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package taskPackage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Division             string   `protobuf:"bytes,2,opt,name=division,proto3" json:"division,omitempty"`
	EmployeeId           string   `protobuf:"bytes,3,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	ShiftId              string   `protobuf:"bytes,4,opt,name=shiftId,proto3" json:"shiftId,omitempty"`
	ManagerId            string   `protobuf:"bytes,5,opt,name=managerId,proto3" json:"managerId,omitempty"`
	AllocatedTimeMin     int64    `protobuf:"varint,6,opt,name=allocatedTimeMin,proto3" json:"allocatedTimeMin,omitempty"`
	SpecialRequests      string   `protobuf:"bytes,7,opt,name=specialRequests,proto3" json:"specialRequests,omitempty"`
	Completed            bool     `protobuf:"varint,8,opt,name=completed,proto3" json:"completed,omitempty"`
	RejectionReason      string   `protobuf:"bytes,9,opt,name=rejectionReason,proto3" json:"rejectionReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *Task) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *Task) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *Task) GetShiftId() string {
	if m != nil {
		return m.ShiftId
	}
	return ""
}

func (m *Task) GetManagerId() string {
	if m != nil {
		return m.ManagerId
	}
	return ""
}

func (m *Task) GetAllocatedTimeMin() int64 {
	if m != nil {
		return m.AllocatedTimeMin
	}
	return 0
}

func (m *Task) GetSpecialRequests() string {
	if m != nil {
		return m.SpecialRequests
	}
	return ""
}

func (m *Task) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Task) GetRejectionReason() string {
	if m != nil {
		return m.RejectionReason
	}
	return ""
}

type TaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AllTaskRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllTaskRequest) Reset()         { *m = AllTaskRequest{} }
func (m *AllTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AllTaskRequest) ProtoMessage()    {}
func (*AllTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *AllTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTaskRequest.Unmarshal(m, b)
}
func (m *AllTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTaskRequest.Marshal(b, m, deterministic)
}
func (m *AllTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTaskRequest.Merge(m, src)
}
func (m *AllTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AllTaskRequest.Size(m)
}
func (m *AllTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllTaskRequest proto.InternalMessageInfo

type ResponsePayload struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Task    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponsePayload) Reset()         { *m = ResponsePayload{} }
func (m *ResponsePayload) String() string { return proto.CompactTextString(m) }
func (*ResponsePayload) ProtoMessage()    {}
func (*ResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *ResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePayload.Unmarshal(m, b)
}
func (m *ResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePayload.Marshal(b, m, deterministic)
}
func (m *ResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePayload.Merge(m, src)
}
func (m *ResponsePayload) XXX_Size() int {
	return xxx_messageInfo_ResponsePayload.Size(m)
}
func (m *ResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePayload proto.InternalMessageInfo

func (m *ResponsePayload) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponsePayload) GetData() *Task {
	if m != nil {
		return m.Data
	}
	return nil
}

type AllTaskResponsePayload struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []*Task  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllTaskResponsePayload) Reset()         { *m = AllTaskResponsePayload{} }
func (m *AllTaskResponsePayload) String() string { return proto.CompactTextString(m) }
func (*AllTaskResponsePayload) ProtoMessage()    {}
func (*AllTaskResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *AllTaskResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTaskResponsePayload.Unmarshal(m, b)
}
func (m *AllTaskResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTaskResponsePayload.Marshal(b, m, deterministic)
}
func (m *AllTaskResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTaskResponsePayload.Merge(m, src)
}
func (m *AllTaskResponsePayload) XXX_Size() int {
	return xxx_messageInfo_AllTaskResponsePayload.Size(m)
}
func (m *AllTaskResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTaskResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_AllTaskResponsePayload proto.InternalMessageInfo

func (m *AllTaskResponsePayload) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AllTaskResponsePayload) GetData() []*Task {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "taskPackage.Task")
	proto.RegisterType((*TaskRequest)(nil), "taskPackage.TaskRequest")
	proto.RegisterType((*AllTaskRequest)(nil), "taskPackage.AllTaskRequest")
	proto.RegisterType((*ResponsePayload)(nil), "taskPackage.ResponsePayload")
	proto.RegisterType((*AllTaskResponsePayload)(nil), "taskPackage.AllTaskResponsePayload")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0xd2, 0xed, 0x9f, 0x89, 0xb4, 0x5d, 0x7c, 0x58, 0x59, 0x65, 0x41, 0x55, 0x10,
	0x52, 0xc4, 0xa1, 0x87, 0xe5, 0x01, 0x2a, 0x54, 0x44, 0x95, 0x03, 0x52, 0x09, 0x45, 0x1c, 0xd1,
	0x10, 0x0f, 0xc5, 0xd4, 0x89, 0x43, 0xec, 0x56, 0xea, 0x23, 0xf1, 0x74, 0xbc, 0x02, 0x8a, 0x5b,
	0xfa, 0x27, 0x45, 0xa0, 0x55, 0x6f, 0x99, 0xef, 0xb3, 0x7f, 0x9e, 0xf9, 0x62, 0x03, 0x58, 0x34,
	0xcb, 0x51, 0x59, 0x69, 0xab, 0x59, 0x58, 0x7f, 0xcf, 0x30, 0x5b, 0xe2, 0x82, 0xa2, 0x9f, 0x3e,
	0xb4, 0xe6, 0x68, 0x96, 0xac, 0x0f, 0xc1, 0x67, 0x29, 0xb8, 0x37, 0xf4, 0xe2, 0x5e, 0xea, 0x27,
	0x82, 0x0d, 0xa0, 0x2b, 0xe4, 0x5a, 0x1a, 0xa9, 0x0b, 0xee, 0x3b, 0x75, 0x5f, 0xb3, 0x67, 0x00,
	0x94, 0x97, 0x4a, 0x6f, 0x88, 0x12, 0xc1, 0x03, 0xe7, 0x1e, 0x29, 0x8c, 0x43, 0xc7, 0x7c, 0x93,
	0x5f, 0x6d, 0x22, 0x78, 0xcb, 0x99, 0x7f, 0x4a, 0x76, 0x07, 0xbd, 0x1c, 0x0b, 0x5c, 0x50, 0x95,
	0x08, 0x7e, 0xe5, 0xbc, 0x83, 0xc0, 0x5e, 0xc2, 0x0d, 0x2a, 0xa5, 0x33, 0xb4, 0x24, 0xe6, 0x32,
	0xa7, 0x77, 0xb2, 0xe0, 0xed, 0xa1, 0x17, 0x07, 0xe9, 0x99, 0xce, 0x62, 0xe8, 0x9b, 0x92, 0x32,
	0x89, 0x2a, 0xa5, 0x1f, 0x2b, 0x32, 0xd6, 0xf0, 0x8e, 0xe3, 0x35, 0xe5, 0xfa, 0xcc, 0x4c, 0xe7,
	0xa5, 0x22, 0x4b, 0x82, 0x77, 0x87, 0x5e, 0xdc, 0x4d, 0x0f, 0x42, 0xcd, 0xa9, 0xe8, 0x3b, 0x65,
	0x56, 0xea, 0x22, 0x25, 0x34, 0xba, 0xe0, 0xbd, 0x2d, 0xa7, 0x21, 0x47, 0x4f, 0x21, 0xac, 0xa3,
	0xda, 0x71, 0xd9, 0x35, 0xf8, 0x87, 0xc0, 0xa4, 0x88, 0x6e, 0xe0, 0xfa, 0xb5, 0x52, 0x47, 0x2b,
	0xa2, 0x19, 0xf4, 0x53, 0x32, 0xa5, 0x2e, 0x0c, 0xcd, 0x70, 0xa3, 0x34, 0x0a, 0x76, 0x0b, 0x6d,
	0x63, 0xd1, 0xae, 0x8c, 0xdb, 0x78, 0x95, 0xee, 0x2a, 0xf6, 0x02, 0x5a, 0x02, 0x2d, 0xba, 0x2c,
	0xc3, 0xfb, 0xc7, 0xa3, 0xa3, 0x7f, 0x34, 0x72, 0x48, 0x67, 0x47, 0x9f, 0xe0, 0x76, 0x7f, 0xc6,
	0x43, 0xc1, 0xc1, 0x3f, 0xc0, 0xf7, 0xbf, 0xfc, 0xed, 0x70, 0x1f, 0xa8, 0x5a, 0xcb, 0x8c, 0xd8,
	0x04, 0x3a, 0x53, 0xb2, 0xee, 0x66, 0xf0, 0xf3, 0x3d, 0xdb, 0xf9, 0x06, 0x77, 0x27, 0x4e, 0xa3,
	0xa3, 0xe8, 0x11, 0x7b, 0x0f, 0xe1, 0x94, 0xec, 0xae, 0x61, 0xc3, 0x9e, 0x9c, 0x2c, 0x3f, 0xcd,
	0x6a, 0xf0, 0xfc, 0xef, 0x66, 0x13, 0x39, 0x06, 0x98, 0x54, 0x84, 0x96, 0x5c, 0x6b, 0xe7, 0xe3,
	0xfc, 0xb7, 0xa7, 0x31, 0xc0, 0xc7, 0x52, 0x5c, 0x00, 0x78, 0x0b, 0xf0, 0x86, 0xea, 0xab, 0x73,
	0x59, 0x38, 0x5f, 0xda, 0xee, 0x35, 0xbe, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x07, 0x0c, 0xc4,
	0x4e, 0x9b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ResponsePayload, error)
	GetAllTasks(ctx context.Context, in *AllTaskRequest, opts ...grpc.CallOption) (*AllTaskResponsePayload, error)
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*ResponsePayload, error)
	UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*ResponsePayload, error)
	DeleteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ResponsePayload, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ResponsePayload, error) {
	out := new(ResponsePayload)
	err := c.cc.Invoke(ctx, "/taskPackage.TaskService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetAllTasks(ctx context.Context, in *AllTaskRequest, opts ...grpc.CallOption) (*AllTaskResponsePayload, error) {
	out := new(AllTaskResponsePayload)
	err := c.cc.Invoke(ctx, "/taskPackage.TaskService/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*ResponsePayload, error) {
	out := new(ResponsePayload)
	err := c.cc.Invoke(ctx, "/taskPackage.TaskService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*ResponsePayload, error) {
	out := new(ResponsePayload)
	err := c.cc.Invoke(ctx, "/taskPackage.TaskService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ResponsePayload, error) {
	out := new(ResponsePayload)
	err := c.cc.Invoke(ctx, "/taskPackage.TaskService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	GetTask(context.Context, *TaskRequest) (*ResponsePayload, error)
	GetAllTasks(context.Context, *AllTaskRequest) (*AllTaskResponsePayload, error)
	CreateTask(context.Context, *Task) (*ResponsePayload, error)
	UpdateTask(context.Context, *Task) (*ResponsePayload, error)
	DeleteTask(context.Context, *TaskRequest) (*ResponsePayload, error)
}

// UnimplementedTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (*UnimplementedTaskServiceServer) GetTask(ctx context.Context, req *TaskRequest) (*ResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedTaskServiceServer) GetAllTasks(ctx context.Context, req *AllTaskRequest) (*AllTaskResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTasks not implemented")
}
func (*UnimplementedTaskServiceServer) CreateTask(ctx context.Context, req *Task) (*ResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedTaskServiceServer) UpdateTask(ctx context.Context, req *Task) (*ResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (*UnimplementedTaskServiceServer) DeleteTask(ctx context.Context, req *TaskRequest) (*ResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskPackage.TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskPackage.TaskService/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetAllTasks(ctx, req.(*AllTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskPackage.TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskPackage.TaskService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskPackage.TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskPackage.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _TaskService_GetAllTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
