apiVersion: v1
kind: ConfigMap
metadata:
    name: analytic-service-config
data:
    PORT: "3000"
    POSTGRES_SERVICE_NAME: "acid-analytic-postgres"
    POSTGRES_USERNAME: root
    POSTGRES_PORT: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: analytic-service-depl
    labels:
        app: analytic-service
spec:
    replicas: 1
    template:
        metadata:
            annotations:
              config.linkerd.io/proxy-log-level: error
            name: analytic-service
            labels:
                app: analytic-service
                deployment: acme-fast
        spec:
            containers:
                - name: analytic-service
                  image: espressotrip/concept-analytic-service
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: analytic-service-config
                      - configMapRef:
                            name: global-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: analytic-service

---
apiVersion: v1
kind: Service
metadata:
    name: analytic-service-srv
spec:
    selector:
        app: analytic-service
    ports:
        - port: 8080
          targetPort: 8080
          name: grpc
