apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-api-config
data:
    PORT: "3000"
    GOOGLE_CALLBACK_URL: "/api/auth/google/redirect"
    GITHUB_CALLBACK_URL: "/api/auth/github/redirect"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-api-depl
    labels:
        app: auth-api
spec:
    replicas: 1
    template:
        metadata:
            annotations:
              config.linkerd.io/proxy-log-level: warn
            name: auth-api
            labels:
                app: auth-api
                deployment: acme-fast
        spec:
            containers:
                - name: auth-api
                  image: espressotrip/concept-auth-api
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: auth-api-config
                      - configMapRef:
                            name: global-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: auth-api

---
apiVersion: v1
kind: Service
metadata:
    name: auth-api-srv
spec:
    selector:
        app: auth-api
    ports:
        - port: 3000
          targetPort: 3000
          name: auth-api
