apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: concept-ingress-srv
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
        - host: acmefast.dev
          http:
              paths:
                # Auth API
                  - path: /api/auth/?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: auth-api-srv
                            port:
                                number: 3000
                # Analytics API
                  - path: /api/analytic/?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: analytic-api-srv
                            port:
                                number: 3000

                # Analytics-Web UI
                  - path: /analytic/?(.*)
                    pathType: Prefix
                    backend:
                      service:
                        name: auth-web-srv
                        port:
                          number: 3000

                # Auth-Web UI
                  - path: /?(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: auth-web-srv
                            port:
                                number: 3000
