apiVersion: v1
kind: ConfigMap
metadata:
    name: employee-dash-api-config
data:
    PORT: "3000"
    EMPLOYEE_GOOGLE_CALLBACK_URL: "/api/auth/google/redirect"
    EMPLOYEE_GITHUB_CALLBACK_URL: "/api/auth/github/redirect"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-dash-api-depl
    labels:
        app: employee-dash-api
spec:
    replicas: 1
    template:
        metadata:
            annotations:
                config.linkerd.io/proxy-log-level: warn
            name: employee-dash-api
            labels:
                app: employee-dash-api
                deployment: acme-fast
        spec:
            containers:
                - name: employee-dash-api
                  image: espressotrip/concept-employee-dash-api
                  imagePullPolicy: IfNotPresent
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                  envFrom:
                      - configMapRef:
                            name: employee-dash-api-config
                      - configMapRef:
                            name: global-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: employee-dash-api

---
apiVersion: v1
kind: Service
metadata:
    name: employee-dash-api-srv
spec:
    selector:
        app: employee-dash-api
    ports:
        - port: 3000
          targetPort: 3000
          name: employee-dash-api
