apiVersion: v1
kind: ConfigMap
metadata:
    name: log-service-config
data:
    LOGGLY_SUBDOMAIN: "concept"
    LOG_PROVIDER_TYPE: "papertrail"
    PAPER_TRAIL_SERVICE: "papertrail-srv"
    PAPER_TRAIL_PORT: "30279"

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: log-service-depl
    labels:
        app: log-service
spec:
    replicas: 1
    template:
        metadata:
            annotations:
                config.linkerd.io/proxy-log-level: warn
            name: log-service
            labels:
                app: log-service
                deployment: acme-fast
        spec:
            containers:
                - name: log-service
                  image: espressotrip/concept-log-service
                  imagePullPolicy: IfNotPresent
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                  envFrom:
                      - configMapRef:
                            name: global-config
                      - configMapRef:
                            name: log-service-config
                      - secretRef:
                            name: global-secret
            restartPolicy: Always
    selector:
        matchLabels:
            app: log-service
