apiVersion: v1
kind: Secret
metadata:
  name: global-secret
data:
  ANALYTIC_POSTGRES_PASSWORD: "UlRwdDZCajlRV1lvajV2MVF1S1JEdFZMR1l5THY4eDFyeGJ2aDlyQzh4UzU4SFltcjB0ZHp2UjlBcXZsY1hWVQ=="

  GOOGLE_SECRET: "R09DU1BYLWlBN0FyX3Q5TVFRdXpqeFhIcy04ODhYemItUmw="
  GOOGLE_CLIENT_ID: 'NjE1MzMyOTExMjMxLWtvMnJoMXRpZDFpZW1pcGNudGtmdnFuc3V0NG5obzYxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t'

  GITHUB_SECRET: "OWVlNmFkNTQyOTljMzQ1MTc4ZTM5NzYyZDBkODIzODRmNGQ3Yjc5OA=="
  GITHUB_CLIENT_ID: 'MDk5OTYwYzAxMjhlMjRjOGFhNjk='

  JWT_KEY: "bXlfc2VjcmV0X2NvZGU="
