// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/employee.proto

package employeePackage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Race                 string   `protobuf:"bytes,5,opt,name=race,proto3" json:"race,omitempty"`
	Position             string   `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	StartDate            string   `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	ShiftPreference      string   `protobuf:"bytes,8,opt,name=shiftPreference,proto3" json:"shiftPreference,omitempty"`
	BranchName           string   `protobuf:"bytes,9,opt,name=branchName,proto3" json:"branchName,omitempty"`
	Region               string   `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Country              string   `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,12,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	Version              int32    `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	SignInType           string   `protobuf:"bytes,15,opt,name=signInType,proto3" json:"signInType,omitempty"`
	ProviderId           string   `protobuf:"bytes,16,opt,name=providerId,proto3" json:"providerId,omitempty"`
	Password             string   `protobuf:"bytes,17,opt,name=password,proto3" json:"password,omitempty"`
	UserRole             string   `protobuf:"bytes,18,opt,name=userRole,proto3" json:"userRole,omitempty"`
	Division             string   `protobuf:"bytes,19,opt,name=division,proto3" json:"division,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_f51afe6743d989cb, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Employee) GetRace() string {
	if m != nil {
		return m.Race
	}
	return ""
}

func (m *Employee) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Employee) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Employee) GetShiftPreference() string {
	if m != nil {
		return m.ShiftPreference
	}
	return ""
}

func (m *Employee) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Employee) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Employee) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Employee) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Employee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Employee) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Employee) GetSignInType() string {
	if m != nil {
		return m.SignInType
	}
	return ""
}

func (m *Employee) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *Employee) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Employee) GetUserRole() string {
	if m != nil {
		return m.UserRole
	}
	return ""
}

func (m *Employee) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type EmployeeUpdate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ShiftPreference      string   `protobuf:"bytes,8,opt,name=shiftPreference,proto3" json:"shiftPreference,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,12,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeUpdate) Reset()         { *m = EmployeeUpdate{} }
func (m *EmployeeUpdate) String() string { return proto.CompactTextString(m) }
func (*EmployeeUpdate) ProtoMessage()    {}
func (*EmployeeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f51afe6743d989cb, []int{1}
}

func (m *EmployeeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeUpdate.Unmarshal(m, b)
}
func (m *EmployeeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeUpdate.Marshal(b, m, deterministic)
}
func (m *EmployeeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeUpdate.Merge(m, src)
}
func (m *EmployeeUpdate) XXX_Size() int {
	return xxx_messageInfo_EmployeeUpdate.Size(m)
}
func (m *EmployeeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeUpdate proto.InternalMessageInfo

func (m *EmployeeUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmployeeUpdate) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EmployeeUpdate) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EmployeeUpdate) GetShiftPreference() string {
	if m != nil {
		return m.ShiftPreference
	}
	return ""
}

func (m *EmployeeUpdate) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type EmployeeId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeId) Reset()         { *m = EmployeeId{} }
func (m *EmployeeId) String() string { return proto.CompactTextString(m) }
func (*EmployeeId) ProtoMessage()    {}
func (*EmployeeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f51afe6743d989cb, []int{2}
}

func (m *EmployeeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeId.Unmarshal(m, b)
}
func (m *EmployeeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeId.Marshal(b, m, deterministic)
}
func (m *EmployeeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeId.Merge(m, src)
}
func (m *EmployeeId) XXX_Size() int {
	return xxx_messageInfo_EmployeeId.Size(m)
}
func (m *EmployeeId) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeId.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeId proto.InternalMessageInfo

func (m *EmployeeId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EmployeeResponsePayload struct {
	Status               int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *Employee `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeResponsePayload) Reset()         { *m = EmployeeResponsePayload{} }
func (m *EmployeeResponsePayload) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponsePayload) ProtoMessage()    {}
func (*EmployeeResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f51afe6743d989cb, []int{3}
}

func (m *EmployeeResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponsePayload.Unmarshal(m, b)
}
func (m *EmployeeResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponsePayload.Marshal(b, m, deterministic)
}
func (m *EmployeeResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponsePayload.Merge(m, src)
}
func (m *EmployeeResponsePayload) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponsePayload.Size(m)
}
func (m *EmployeeResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponsePayload proto.InternalMessageInfo

func (m *EmployeeResponsePayload) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EmployeeResponsePayload) GetData() *Employee {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "employeePackage.Employee")
	proto.RegisterType((*EmployeeUpdate)(nil), "employeePackage.EmployeeUpdate")
	proto.RegisterType((*EmployeeId)(nil), "employeePackage.EmployeeId")
	proto.RegisterType((*EmployeeResponsePayload)(nil), "employeePackage.EmployeeResponsePayload")
}

func init() { proto.RegisterFile("proto/employee.proto", fileDescriptor_f51afe6743d989cb) }

var fileDescriptor_f51afe6743d989cb = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x5f, 0x8f, 0x12, 0x31,
	0x14, 0xc5, 0x05, 0x81, 0x85, 0x8b, 0x82, 0xd6, 0x8d, 0xd6, 0x75, 0x63, 0xc8, 0x3c, 0xf1, 0x22,
	0x26, 0xeb, 0x57, 0xd0, 0x18, 0x5e, 0x36, 0x64, 0xfc, 0xf3, 0x6c, 0x99, 0x5e, 0xa0, 0x71, 0x98,
	0x4e, 0x6e, 0x0b, 0x86, 0xef, 0xe2, 0xb3, 0x9f, 0xd3, 0xf4, 0x76, 0x0a, 0x2b, 0xc9, 0x46, 0x1f,
	0x7c, 0xe3, 0x9c, 0xdf, 0xcd, 0xe1, 0xcc, 0x6d, 0x0b, 0x97, 0x35, 0x59, 0x6f, 0xdf, 0xe2, 0xb6,
	0x2e, 0xed, 0x01, 0x71, 0xc6, 0x52, 0x8c, 0x93, 0x5e, 0xa8, 0xe2, 0xbb, 0x5a, 0x63, 0xf6, 0xb3,
	0x03, 0xfd, 0x0f, 0x8d, 0x27, 0x46, 0xd0, 0x36, 0x5a, 0xb6, 0x26, 0xad, 0xe9, 0x20, 0x6f, 0x1b,
	0x2d, 0xae, 0x61, 0xb0, 0x32, 0xe4, 0xfc, 0xad, 0xda, 0xa2, 0x6c, 0xb3, 0x7d, 0x32, 0xc4, 0x15,
	0xf4, 0x4b, 0xd5, 0xc0, 0x87, 0x0c, 0x8f, 0x5a, 0x3c, 0x87, 0xde, 0x1a, 0x2b, 0x8d, 0x24, 0x3b,
	0x4c, 0x1a, 0x25, 0x04, 0x74, 0x48, 0x15, 0x28, 0xbb, 0xec, 0xf2, 0xef, 0x90, 0x53, 0x5b, 0x67,
	0xbc, 0xb1, 0x95, 0xec, 0xc5, 0x9c, 0xa4, 0x43, 0x03, 0xe7, 0x15, 0xf9, 0xf7, 0xca, 0xa3, 0xbc,
	0x88, 0x0d, 0x8e, 0x86, 0x98, 0xc2, 0xd8, 0x6d, 0xcc, 0xca, 0x2f, 0x08, 0x57, 0x48, 0x58, 0x15,
	0x28, 0xfb, 0x3c, 0x73, 0x6e, 0x8b, 0xd7, 0x00, 0x4b, 0x52, 0x55, 0xb1, 0xe1, 0xb6, 0x03, 0x1e,
	0xba, 0xe3, 0x84, 0xbe, 0x84, 0xeb, 0xd0, 0x00, 0x62, 0xdf, 0xa8, 0x84, 0x84, 0x8b, 0xc2, 0xee,
	0x2a, 0x4f, 0x07, 0x39, 0x64, 0x90, 0xa4, 0x98, 0xc0, 0xb0, 0xde, 0xd8, 0x0a, 0x6f, 0x77, 0xdb,
	0x25, 0x92, 0x7c, 0xc4, 0xf4, 0xae, 0x25, 0x2e, 0xa1, 0x8b, 0x5b, 0x65, 0x4a, 0xf9, 0x98, 0x59,
	0x14, 0x21, 0x71, 0x8f, 0xe4, 0xc2, 0x5f, 0x8d, 0x26, 0xad, 0x69, 0x37, 0x4f, 0x32, 0x74, 0x74,
	0x66, 0x5d, 0xcd, 0xab, 0xcf, 0x87, 0x1a, 0xe5, 0x38, 0x76, 0x3c, 0x39, 0x81, 0xd7, 0x64, 0xf7,
	0x46, 0x23, 0xcd, 0xb5, 0x7c, 0x12, 0xf9, 0xc9, 0xe1, 0x3d, 0x2a, 0xe7, 0x7e, 0x58, 0xd2, 0xf2,
	0x69, 0xb3, 0xc7, 0x46, 0x07, 0xb6, 0x73, 0x48, 0xb9, 0x2d, 0x51, 0x8a, 0xc8, 0x92, 0x0e, 0x4c,
	0x9b, 0xbd, 0xe1, 0x4a, 0xcf, 0x22, 0x4b, 0x3a, 0xfb, 0xd5, 0x82, 0x51, 0xba, 0x1e, 0x5f, 0x6a,
	0x1d, 0x96, 0xfe, 0xff, 0x2e, 0xc9, 0xbf, 0x1f, 0xdf, 0x5f, 0x97, 0x9d, 0x5d, 0x03, 0xa4, 0x9e,
	0x73, 0x7d, 0xde, 0x31, 0xfb, 0x06, 0x2f, 0x12, 0xcd, 0xd1, 0xd5, 0xb6, 0x72, 0xb8, 0x50, 0x87,
	0xd2, 0x2a, 0x1d, 0x4e, 0xde, 0x79, 0xe5, 0x77, 0x8e, 0xc7, 0xbb, 0x79, 0xa3, 0xc4, 0x1b, 0xe8,
	0x68, 0xe5, 0x15, 0x7f, 0xd1, 0xf0, 0xe6, 0xe5, 0xec, 0xec, 0xe1, 0xcc, 0x8e, 0x79, 0x3c, 0x76,
	0x63, 0x60, 0x9c, 0x9c, 0x4f, 0x48, 0x7b, 0x53, 0xa0, 0xf8, 0x0a, 0xc3, 0x8f, 0xe8, 0x8f, 0x8f,
	0xeb, 0xd5, 0xbd, 0x11, 0x73, 0x7d, 0x35, 0xbd, 0x3f, 0xff, 0xcf, 0xbe, 0xd9, 0x83, 0x65, 0x8f,
	0x9f, 0xf2, 0xbb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0x65, 0x99, 0xe1, 0xe2, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployee(ctx context.Context, in *EmployeeId, opts ...grpc.CallOption) (*EmployeeResponsePayload, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeId, opts ...grpc.CallOption) (*EmployeeResponsePayload, error) {
	out := new(EmployeeResponsePayload)
	err := c.cc.Invoke(ctx, "/employeePackage.EmployeeService/GetEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetEmployee(context.Context, *EmployeeId) (*EmployeeResponsePayload, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetEmployee(ctx context.Context, req *EmployeeId) (*EmployeeResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeePackage.EmployeeService/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, req.(*EmployeeId))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "employeePackage.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployee",
			Handler:    _EmployeeService_GetEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/employee.proto",
}
