apiVersion: apps/v1
kind: Deployment
metadata:
    name: division-mongo-dpl
    labels:
        app: division-mongo
spec:
    replicas: 1
    template:
        metadata:
            name: division-mongo
            labels:
                app: division-mongo
        spec:
            containers:
                - name: division-mongo
                  image: mongo:4.2.18
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: division-config
                  volumeMounts:
                      - mountPath: /data/db
                        name: division-mongo-storage
            volumes:
                - name: division-mongo-storage
                  persistentVolumeClaim:
                      claimName: division-pv-claim
            restartPolicy: Always
    selector:
        matchLabels:
            app: division-mongo

---
apiVersion: v1
kind: Service
metadata:
    name: division-mongo-srv
spec:
    selector:
        app: division-mongo
    ports:
        - port: 27017
          targetPort: 27017
          name: division-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: division-storage
spec:
    claimRef:
        name: division-pv-claim
        namespace: default
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        type: DirectoryOrCreate
        path: /data/division

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: division-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    volumeName: division-storage

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: division-config
data:
    MONGODB_ROOT_PASSWORD: "8103"
