apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-mongo-dpl
    labels:
        app: employee-mongo
spec:
    replicas: 1
    template:
        metadata:
            annotations:
                config.linkerd.io/proxy-log-level: error
            name: employee-mongo
            labels:
                app: employee-mongo
        spec:
            containers:
                - name: employee-mongo
                  image: mongo:4.2.18
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                      - mountPath: /data/db
                        name: employee-mongo-storage
            volumes:
                - name: employee-mongo-storage
                  persistentVolumeClaim:
                      claimName: employee-pv-claim
            restartPolicy: Always
    selector:
        matchLabels:
            app: employee-mongo

---
apiVersion: v1
kind: Service
metadata:
    name: employee-mongo-srv
spec:
    selector:
        app: employee-mongo
    ports:
        - port: 27017
          targetPort: 27017
          name: employee-db

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: employee-storage
spec:
    persistentVolumeReclaimPolicy: Delete
    claimRef:
        name: employee-pv-claim
        namespace: default
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        type: DirectoryOrCreate
        path: /data/employee

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: employee-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    volumeName: employee-storage
