apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-depl
    labels:
        app: rabbitmq
spec:
    replicas: 1
    template:
        metadata:
            annotations:
                config.linkerd.io/proxy-log-level: error
            name: rabbitmq
            labels:
                app: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: rabbitmq:management-alpine
                  imagePullPolicy: IfNotPresent
            restartPolicy: Always
    selector:
        matchLabels:
            app: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
    name: rabbit-cluster
spec:
    selector:
        app: rabbitmq
    ports:
        - port: 5672
          name: rabbit
        - port: 15672
          name: management
    type: ClusterIP
---

