apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-mongo-dpl
    labels:
        app: task-mongo
spec:
    replicas: 1
    template:
        metadata:
            name: task-mongo
            labels:
                app: task-mongo
        spec:
            containers:
                - name: task-mongo
                  image: mongo:4.2.18
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: task-config
                  volumeMounts:
                      - mountPath: /data/db
                        name: task-mongo-storage
            volumes:
                - name: task-mongo-storage
                  persistentVolumeClaim:
                      claimName: task-pv-claim
            restartPolicy: Always
    selector:
        matchLabels:
            app: task-mongo

---
apiVersion: v1
kind: Service
metadata:
    name: task-mongo-srv
spec:
    selector:
        app: task-mongo
    ports:
        - port: 27017
          targetPort: 27017
          name: task-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: task-storage
spec:
    claimRef:
        name: task-pv-claim
        namespace: default
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        type: DirectoryOrCreate
        path: /data/task

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: task-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    volumeName: task-storage

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: task-config
data:
    MONGODB_ROOT_PASSWORD: "8103"
