---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: order-mongo
spec:
    members: 1
    type: ReplicaSet
    version: "4.2.6"
    security:
        authentication:
            modes: ["SCRAM"]
    users:
        - name: root
          db: order
          passwordSecretRef:
              name: order-mongo-password
          roles:
              - name: clusterAdmin
                db: admin
              - name: userAdminAnyDatabase
                db: admin
          scramCredentialsSecretName: my-scram
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib

---
apiVersion: v1
kind: Secret
metadata:
    name: order-mongo-password
type: Opaque
stringData:
    password: "8103"
